### ISSUE TITLE
Renew period without passing challenge

### ISSUE THREAD

**Issue by avelinoingrammicro** [alexpeattie/letsencrypt-fromscratch#8]
Hello!

Based on the guide, the validity period of an authorization is 300 days, but I cannot this anywhere in the official documentation.

What I have found is that authorizations are cached for **30** days (last question): https://letsencrypt.org/docs/faq/.

Could you confirm this information, please?

Thanks for the guide!

**Comment by alexpeattie** [comment]
Thanks @avelinoingrammicro - and sorry for taking 18 months to reply to this 🙈 ! You're quite right - I've updated the relevant part of the guide and adding some contextual info about relying on validated authz [here](https://github.com/alexpeattie/letsencrypt-fromscratch#5-issuing-the-certificate-tada)
